name: E2E Tests

on:
  pull_request:
    branches:
      - next
      - master

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      RESOLVER_DOMAIN: ${{ vars.RESOLVER_DOMAIN }}
      NODE_ENV: test
      OBJECT_STORAGE_ENDPOINT: ${{ vars.OBJECT_STORAGE_ENDPOINT }}
      OBJECT_STORAGE_PORT: ${{ vars.OBJECT_STORAGE_PORT }}
      OBJECT_STORAGE_USE_SSL: ${{ vars.OBJECT_STORAGE_USE_SSL }}
      OBJECT_STORAGE_ACCESS_KEY: ${{ secrets.OBJECT_STORAGE_ACCESS_KEY }}
      OBJECT_STORAGE_SECRET_KEY: ${{ secrets.OBJECT_STORAGE_SECRET_KEY }}
      OBJECT_STORAGE_BUCKET_NAME: ${{ vars.OBJECT_STORAGE_BUCKET_NAME }}
      OBJECT_STORAGE_PATH_STYLE: ${{ vars.OBJECT_STORAGE_PATH_STYLE }}
      IDENTIFIER_PATH: ${{ vars.IDENTIFIER_PATH }}
      API_KEY: ${{ secrets.API_KEY }}
      APP_NAME: ${{ vars.APP_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "21" # install Node.js v21.x
          cache: npm
          cache-dependency-path: app/package-lock.json # cache dependencies for the app

      # Install dependencies for running E2E tests
      - name: Install dependencies
        run: npm ci
        working-directory: app

      - name: Start docker compose
        run: docker compose -f app/docker-compose.yaml up -d # Start docker compose in the background

      # Run E2E tests and force exit after all tests have completed
      - name: Run E2E tests
        run: npm run test:e2e -- --forceExit
        working-directory: app

      - name: Stop docker compose
        run: docker compose -f app/docker-compose.yaml down # Stop docker compose after all tests have completed
